version: '3'
services:
  db:
    image: docker.io/postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - caker-db-data:/var/lib/postgresql/data

  adminer:
    image: docker.io/adminer
    depends_on: db
    ports:
      - "5431:8080"
    depends_on:
      - db

volumes:
  caker-db-data:
